export const MICROSERVICE = {
    ACCOUNT_SERVICE: 'ACCOUNT_SERVICE',
    TRANSACTION_SERVICE: 'TRANSACTION_SERVICE',
    USER_SERVICE: 'USER_SERVICE',
    PAYMENT_SERVICE: 'PAYMENT_SERVICE',
    LEDGER_SERVICE: 'LEDGER_SERVICE',
    FX_SERVICE: 'FX_SERVICE',
    PAYROLL_SERVICE: 'PAYROLL_SERVICE',
    NOTIFICATION_SERVICE: 'NOTIFICATION_SERVICE'

}